language: c

before_install:
        - sudo apt-get update -qq

install:
        # Install protobuf-2.5.0
        - wget http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz
        - tar -xzvf protobuf-2.5.0.tar.gz
        - cd protobuf-2.5.0 && ./configure
        - make -j8
        - sudo make install && sudo ldconfig
        - cd ../

script:
        - ./autogen.sh
        - ./configure
        - make -j8
        - make check
        - sudo make install
